# Auto-generated by grail — this is what Monty actually executes

try:
    sorted_preview = ['alpha', 'beta', 'gamma']
    result = {'file_name': file_name, 'sorted_preview': sorted_preview}
except Exception as exc:
    result = {'error': str(exc)}
result