# Auto-generated by grail — this is what Monty actually executes

await ensure_dir(state_dir)
filename = f"{name.replace(' ', '_').lower()}.txt"
filepath = f'{state_dir}/{filename}'
lines = [f'status:{status}', f'priority:{priority}', f'note:{note}']
await write_file(filepath, '\n'.join(lines))
result = {'result': f"Stored entry '{name}'", 'name': name, 'status': status, 'priority': priority, 'note': note}
result