# Auto-generated by grail — do not edit

state_dir: str
name: str
status: str
priority: str
note: str

async def ensure_dir(path: str) -> None:
    ...

async def write_file(path: str, content: str) -> None:
    ...
