# Auto-generated by grail — do not edit

state_dir: str
style: str

async def ensure_dir(path: str) -> None:
    ...

async def list_dir(path: str) -> list[str]:
    ...

async def read_file(path: str) -> str:
    ...
