# Auto-generated by grail — this is what Monty actually executes

try:
    target = file_name if file_name and file_name != 'None' else None
    action = 'appended' if target else 'printed'
    result = {'content': content, 'file_name': target, 'action': action}
except Exception as exc:
    result = {'error': str(exc)}
result