# Auto-generated by grail — this is what Monty actually executes

if style == 'bullet':
    formatted = 'Formatted Summary:\n' + raw_summary.replace('- ', '* ')
else:
    formatted = 'Formatted Summary:\n' + raw_summary
result = {'formatted': formatted, 'style': style}
result